<a href="https://colab.research.google.com/github/snehasri2600/Testing-Only/blob/main/FSHRI_Final_Dataset_Download_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# ============================================================
# INSTALL DEPENDENCIES
# ============================================================
!pip install geopandas -q

import geopandas as gpd
import pandas as pd

In [29]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [30]:
from shapely.geometry import shape
fvi_original = pd.read_json('https://data.cityofnewyork.us/resource/mrjc-v9pm.json?$limit=99999999999')
fvi_original['the_geom'] = fvi_original['the_geom'].apply(shape)
fvi_gdf = gpd.GeoDataFrame(fvi_original, geometry='the_geom')

In [31]:
# ============================================================
# STEP 1: UPDATE THESE FILENAMES TO MATCH YOUR FILES
# ============================================================                # FVI / FSHRI GeoJSON
income_file         = "/content/drive/MyDrive/ColabNotebooks/PIT_Presentation/Tract_2.csv"              # ACS median income CSV
neighborhood_file   = "/content/drive/MyDrive/ColabNotebooks/PIT_Presentation/2020_Census_Tracts_20260318.zip"           # tract-to-neighborhood shapefile

In [32]:
income_gdf = gpd.read_file(income_file)
neighborhoods_gdf = gpd.read_file(neighborhood_file)

In [33]:
display(fvi_gdf.head())
display(income_gdf.head())
display(neighborhoods_gdf.head())

,the_geom,geoid,fshri,ss_80s,ss_cur,ss_50s,tid_80s,tid_20s,tid_50s
0,"MULTIPOLYGON (((-73.90183 40.81915, -73.90167 ...",36005008500,5.0,NaN,NaN,NaN,NaN,NaN,NaN
1,"MULTIPOLYGON (((-73.84472 40.68071, -73.84307 ...",36081008600,5.0,NaN,NaN,NaN,NaN,NaN,NaN
2,"MULTIPOLYGON (((-73.95776 40.60099, -73.95683 ...",36047058000,5.0,2.0,NaN,NaN,NaN,NaN,NaN
3,"MULTIPOLYGON (((-73.9623 40.62996, -73.96137 4...",36047053200,5.0,NaN,NaN,NaN,NaN,NaN,NaN
4,"MULTIPOLYGON (((-73.93859 40.76682, -73.93618 ...",36081004500,5.0,5.0,2.0,5.0,NaN,NaN,NaN

,Object ID,Geographic Identifier - FIPS Code,Tract Name,Area of Land (Square Meters),Area of Water (Square Meters),State Name,County Name,Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range),Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range) - Margin of Error,"Median Household Income in past 12 months, Householder under 25 years",...,Total Households,Total Households - Margin of Error,Households with any self-employment income in past 12 months,Households with any self-employment income in past 12 months - Margin of Error,Households with no self-employment income in past 12 months,Households with no self-employment income in past 12 months - Margin of Error,Percent of households with any self-employment income,Percent of households with any self-employment income - Margin of Error,Shape Area,Shape Length
0,1,12009062115,Census Tract 621.15,9044814,0,Florida,Brevard County,71268,25187,,...,815,218,180,186,635,139,22.1,22.0442154031738,11731331.1464844,13977.6534429529
1,2,12009062301,Census Tract 623.01,2682013,14427,Florida,Brevard County,41125,11466,,...,1341,266,72,64,1269,259,5.4,4.65220877431107,3495468.79101563,8558.00189353554
2,3,12009062302,Census Tract 623.02,2831784,0,Florida,Brevard County,35480,8242,,...,1563,354,62,49,1501,356,4,3.00350718758752,3672045.16210938,8991.1986135111
3,4,12009062401,Census Tract 624.01,6137867,332858,Florida,Brevard County,52057,4179,,...,922,186,99,91,823,165,10.7,9.62921310374469,8391051.68945313,13863.2473317914
4,5,12009062402,Census Tract 624.02,5882534,2843,Florida,Brevard County,34810,12318,67634,...,2385,369,217,154,2168,416,9.1,6.30170886439203,7629695.20703125,12996.4643068565

,ctlabel,borocode,boroname,ct2020,boroct2020,cdeligibil,ntaname,nta2020,cdta2020,cdtaname,geoid,shape_leng,shape_area,geometry
0,1,1,Manhattan,000100,1000100,I,The Battery-Governors Island-Ellis Island-Libe...,MN0191,MN01,MN01 Financial District-Tribeca (CD 1 Equivalent),36061000100,10833.043929,1.843005e+06,"MULTIPOLYGON (((-74.04388 40.69019, -74.04351 ..."
1,22.01,1,Manhattan,002201,1002201,E,Lower East Side,MN0302,MN03,MN03 Lower East Side-Chinatown (CD 3 Equivalent),36061002201,5779.062607,1.740174e+06,"POLYGON ((-73.97875 40.71993, -73.97879 40.719..."
2,26.02,1,Manhattan,002602,1002602,E,East Village,MN0303,MN03,MN03 Lower East Side-Chinatown (CD 3 Equivalent),36061002602,4491.203220,1.114857e+06,"POLYGON ((-73.97559 40.72428, -73.97593 40.723..."
3,28,1,Manhattan,002800,1002800,E,East Village,MN0303,MN03,MN03 Lower East Side-Chinatown (CD 3 Equivalent),36061002800,5627.555089,1.973679e+06,"POLYGON ((-73.9733 40.72743, -73.9738 40.72675..."
4,34,1,Manhattan,003400,1003400,I,East Village,MN0303,MN03,MN03 Lower East Side-Chinatown (CD 3 Equivalent),36061003400,5503.307044,1.718452e+06,"POLYGON ((-73.97803 40.72943, -73.97806 40.729..."

In [34]:
print(income_gdf.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Object ID', 'Geographic Identifier - FIPS Code', 'Tract Name',
       'Area of Land (Square Meters)', 'Area of Water (Square Meters)',
       'State Name', 'County Name',
       'Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range)',
       'Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range) - Margin of Error',
       'Median Household Income in past 12 months, Householder under 25 years',
       'Median Household Income in past 12 months, Householder under 25 years - Margin of Error',
       'Median Household Income in past 12 months, Householder 25 to 44 years',
       'Median Household Income in past 12 months, Householder 25 to 44 years - Margin of Error',
       'Median Household Income in past 12 months, Householder 45 to 64 years',
       'Median Household Income in past 12 months, Householder 45 to 64 years - Margin of Error',
       'Median Household Income in past 12 months, Householder 65 years and over',
       'Median Household Income in past 12 months, Householder 65 years and over - Margin of Error',
       'Median Household Income in past 12 months, Black or African American Alone Householder',
       'Median Household Income in past 12 months, Black or African American Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, American Indian and Alaska Native Alone Householder',
       'Median Household Income in past 12 months, American Indian and Alaska Native Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Asian Alone Householder',
       'Median Household Income in past 12 months, Asian Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Native Hawaiian and Other Pacific Islander Alone Householder',
       'Median Household Income in past 12 months, Native Hawaiian and Other Pacific Islander Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Some Other Race Alone Householder',
       'Median Household Income in past 12 months, Some Other Race Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Two or More Races Householder',
       'Median Household Income in past 12 months, Two or More Races Householder - Margin of Error',
       'Median Household Income in past 12 months, White alone, not Hispanic Householder',
       'Median Household Income in past 12 months, White alone, not Hispanic Householder - Margin of Error',
       'Median Household Income in past 12 months, Hispanic or Latino Householder',
       'Median Household Income in past 12 months, Hispanic or Latino Householder - Margin of Error',
       'Total Households', 'Total Households - Margin of Error',
       'Households with any self-employment income in past 12 months',
       'Households with any self-employment income in past 12 months - Margin of Error',
       'Households with no self-employment income in past 12 months',
       'Households with no self-employment income in past 12 months - Margin of Error',
       'Percent of households with any self-employment income',
       'Percent of households with any self-employment income - Margin of Error',
       'Shape Area', 'Shape Length'],
      dtype='object')>

In [36]:
# Rename the income GEOID column to match the others
income_gdf = income_gdf.rename(columns={"Geographic Identifier - FIPS Code": "geoid"})

# Ensure all three are strings, zero-padded to 11 digits
fvi_gdf["geoid"] = fvi_gdf["geoid"].astype(str).str.zfill(11)
income_gdf["geoid"] = income_gdf["geoid"].astype(str).str.zfill(11)
neighborhoods_gdf["geoid"] = neighborhoods_gdf["geoid"].astype(str).str.zfill(11)

# Merge
merged = fvi_gdf.merge(income, on="geoid", how="left")
merged = merged.merge(neighborhoods_gdf, on="geoid", how="left")

print(merged.shape)
print(merged.isnull().sum())

(2209, 64)
the_geom         0
geoid            0
fshri            2
ss_80s        1597
ss_cur        1848
              ...
cdta2020         0
cdtaname         0
shape_leng       0
shape_area       0
geometry         0
Length: 64, dtype: int64

In [38]:
desired_counties = [
    'Bronx County',
    'Kings County', # Brooklyn
    'Richmond County', # Staten Island
    'New York County', # Manhattan
    'Queens County'
]

# Filter the merged DataFrame
merged_filtered = merged[merged['County Name'].isin(desired_counties)]

print(f"Shape of filtered DataFrame: {merged_filtered.shape}")
print(merged_filtered['County Name'].value_counts())

Shape of filtered DataFrame: (2209, 64)
County Name
Kings County       774
Queens County      678
Bronx County       340
New York County    300
Richmond County    117
Name: count, dtype: int64

In [39]:
display(merged_filtered)

,the_geom,geoid,fshri,ss_80s,ss_cur,ss_50s,tid_80s,tid_20s,tid_50s,Object ID,...,ct2020,boroct2020,cdeligibil,ntaname,nta2020,cdta2020,cdtaname,shape_leng,shape_area,geometry
0,"MULTIPOLYGON (((-73.90183 40.81915, -73.90167 ...",36005008500,5.0,NaN,NaN,NaN,NaN,NaN,NaN,67464,...,008500,2008500,E,Longwood,BX0202,BX02,BX02 Longwood-Hunts Point (CD 2 Approximation),6463.499306,1.966132e+06,"POLYGON ((-73.89704 40.8168, -73.89621 40.8163..."
1,"MULTIPOLYGON (((-73.84472 40.68071, -73.84307 ...",36081008600,5.0,NaN,NaN,NaN,NaN,NaN,NaN,69631,...,008600,4008600,I,Ozone Park,QN1002,QN10,QN10 South Ozone Park-Howard Beach (CD 10 Appr...,8145.399567,3.562476e+06,"POLYGON ((-73.83952 40.67996, -73.83794 40.676..."
2,"MULTIPOLYGON (((-73.95776 40.60099, -73.95683 ...",36047058000,5.0,2.0,NaN,NaN,NaN,NaN,NaN,68577,...,058000,3058000,E,Madison,BK1502,BK15,BK15 Sheepshead Bay-Gravesend (East) (CD 15 Ap...,5340.456417,1.707766e+06,"POLYGON ((-73.95315 40.59703, -73.95411 40.596..."
3,"MULTIPOLYGON (((-73.9623 40.62996, -73.96137 4...",36047053200,5.0,NaN,NaN,NaN,NaN,NaN,NaN,68533,...,053200,3053200,E,Midwood,BK1403,BK14,BK14 Flatbush-Midwood (CD 14 Approximation),6887.340443,1.876179e+06,"POLYGON ((-73.95899 40.62789, -73.95854 40.625..."
4,"MULTIPOLYGON (((-73.93859 40.76682, -73.93618 ...",36081004500,5.0,5.0,2.0,5.0,NaN,NaN,NaN,69605,...,004500,4004500,I,Queensbridge-Ravenswood-Dutch Kills,QN0105,QN01,QN01 Astoria-Queensbridge (CD 1 Equivalent),7941.412066,2.375492e+06,"POLYGON ((-73.93494 40.76701, -73.93363 40.766..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2204,"MULTIPOLYGON (((-73.98639 40.74592, -73.98595 ...",36061007400,1.0,NaN,NaN,NaN,NaN,NaN,NaN,69208,...,007400,1007400,I,Midtown South-Flatiron-Union Square,MN0501,MN05,MN05 Midtown-Flatiron-Union Square (CD 5 Appro...,5726.157650,1.879420e+06,"POLYGON ((-73.98085 40.74775, -73.98134 40.747..."
2205,"MULTIPOLYGON (((-74.02064 40.73039, -74.02006 ...",36061006900,1.0,3.0,2.0,3.0,NaN,NaN,NaN,69202,...,006900,1006900,I,West Village,MN0203,MN02,MN02 Greenwich Village-SoHo (CD 2 Equivalent),7531.257104,2.362610e+06,"POLYGON ((-74.00662 40.73167, -74.00674 40.730..."
2206,"MULTIPOLYGON (((-73.96439 40.80734, -73.96417 ...",36061020300,1.0,NaN,NaN,NaN,NaN,NaN,NaN,69364,...,020300,1020300,I,Morningside Heights,MN0901,MN09,MN09 Morningside Heights-Hamilton Heights (CD ...,6065.202681,1.916857e+06,"POLYGON ((-73.95827 40.81063, -73.95872 40.810..."
2207,"MULTIPOLYGON (((-73.90307 40.80988, -73.89917 ...",36005009302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67471,...,009302,2009302,I,Hunts Point,BX0201,BX02,BX02 Longwood-Hunts Point (CD 2 Approximation),32163.459912,1.908350e+07,"POLYGON ((-73.88201 40.81083, -73.88182 40.810..."
2208,"MULTIPOLYGON (((-73.84494 40.84821, -73.84359 ...",36005028400,NaN,1.0,2.0,1.0,NaN,NaN,NaN,67619,...,028400,2028400,I,Hutchinson Metro Center,BX1161,BX11,BX11 Pelham Parkway-Morris Park (CD 11 Approxi...,20672.707207,1.218138e+07,"POLYGON ((-73.83129 40.85543, -73.83157 40.855..."

In [40]:
print(merged_filtered.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['the_geom', 'geoid', 'fshri', 'ss_80s', 'ss_cur', 'ss_50s', 'tid_80s',
       'tid_20s', 'tid_50s', 'Object ID', 'Tract Name',
       'Area of Land (Square Meters)', 'Area of Water (Square Meters)',
       'State Name', 'County Name',
       'Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range)',
       'Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range) - Margin of Error',
       'Median Household Income in past 12 months, Householder under 25 years',
       'Median Household Income in past 12 months, Householder under 25 years - Margin of Error',
       'Median Household Income in past 12 months, Householder 25 to 44 years',
       'Median Household Income in past 12 months, Householder 25 to 44 years - Margin of Error',
       'Median Household Income in past 12 months, Householder 45 to 64 years',
       'Median Household Income in past 12 months, Householder 45 to 64 years - Margin of Error',
       'Median Household Income in past 12 months, Householder 65 years and over',
       'Median Household Income in past 12 months, Householder 65 years and over - Margin of Error',
       'Median Household Income in past 12 months, Black or African American Alone Householder',
       'Median Household Income in past 12 months, Black or African American Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, American Indian and Alaska Native Alone Householder',
       'Median Household Income in past 12 months, American Indian and Alaska Native Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Asian Alone Householder',
       'Median Household Income in past 12 months, Asian Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Native Hawaiian and Other Pacific Islander Alone Householder',
       'Median Household Income in past 12 months, Native Hawaiian and Other Pacific Islander Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Some Other Race Alone Householder',
       'Median Household Income in past 12 months, Some Other Race Alone Householder - Margin of Error',
       'Median Household Income in past 12 months, Two or More Races Householder',
       'Median Household Income in past 12 months, Two or More Races Householder - Margin of Error',
       'Median Household Income in past 12 months, White alone, not Hispanic Householder',
       'Median Household Income in past 12 months, White alone, not Hispanic Householder - Margin of Error',
       'Median Household Income in past 12 months, Hispanic or Latino Householder',
       'Median Household Income in past 12 months, Hispanic or Latino Householder - Margin of Error',
       'Total Households', 'Total Households - Margin of Error',
       'Households with any self-employment income in past 12 months',
       'Households with any self-employment income in past 12 months - Margin of Error',
       'Households with no self-employment income in past 12 months',
       'Households with no self-employment income in past 12 months - Margin of Error',
       'Percent of households with any self-employment income',
       'Percent of households with any self-employment income - Margin of Error',
       'Shape Area', 'Shape Length', 'ctlabel', 'borocode', 'boroname',
       'ct2020', 'boroct2020', 'cdeligibil', 'ntaname', 'nta2020', 'cdta2020',
       'cdtaname', 'shape_leng', 'shape_area', 'geometry'],
      dtype='object')>

In [41]:
columns_to_keep = [
    'the_geom',
    'geoid',
    'fshri',
    'Tract Name',
    'State Name',
    'County Name',
    'Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range)',
    'boroname',
    'ntaname',
    'nta2020',
    'cdta2020',
    'cdtaname',
    'shape_leng',
    'shape_area',
    'geometry'
]

final_gdf = merged_filtered[columns_to_keep]

display(final_gdf.head())
print(f"Shape of final DataFrame: {final_gdf.shape}")

,the_geom,geoid,fshri,Tract Name,State Name,County Name,Median Household Income in past 12 months (inflation-adjusted dollars to last year of 5-year range),boroname,ntaname,nta2020,cdta2020,cdtaname,shape_leng,shape_area,geometry
0,"MULTIPOLYGON (((-73.90183 40.81915, -73.90167 ...",36005008500,5.0,Census Tract 85,New York,Bronx County,41535,Bronx,Longwood,BX0202,BX02,BX02 Longwood-Hunts Point (CD 2 Approximation),6463.499306,1.966132e+06,"POLYGON ((-73.89704 40.8168, -73.89621 40.8163..."
1,"MULTIPOLYGON (((-73.84472 40.68071, -73.84307 ...",36081008600,5.0,Census Tract 86,New York,Queens County,89667,Queens,Ozone Park,QN1002,QN10,QN10 South Ozone Park-Howard Beach (CD 10 Appr...,8145.399567,3.562476e+06,"POLYGON ((-73.83952 40.67996, -73.83794 40.676..."
2,"MULTIPOLYGON (((-73.95776 40.60099, -73.95683 ...",36047058000,5.0,Census Tract 580,New York,Kings County,38945,Brooklyn,Madison,BK1502,BK15,BK15 Sheepshead Bay-Gravesend (East) (CD 15 Ap...,5340.456417,1.707766e+06,"POLYGON ((-73.95315 40.59703, -73.95411 40.596..."
3,"MULTIPOLYGON (((-73.9623 40.62996, -73.96137 4...",36047053200,5.0,Census Tract 532,New York,Kings County,72500,Brooklyn,Midwood,BK1403,BK14,BK14 Flatbush-Midwood (CD 14 Approximation),6887.340443,1.876179e+06,"POLYGON ((-73.95899 40.62789, -73.95854 40.625..."
4,"MULTIPOLYGON (((-73.93859 40.76682, -73.93618 ...",36081004500,5.0,Census Tract 45,New York,Queens County,97462,Queens,Queensbridge-Ravenswood-Dutch Kills,QN0105,QN01,QN01 Astoria-Queensbridge (CD 1 Equivalent),7941.412066,2.375492e+06,"POLYGON ((-73.93494 40.76701, -73.93363 40.766..."

Shape of final DataFrame: (2209, 15)